In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import IPython
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.metrics import confusion_matrix



In [2]:
train = pd.read_csv("TRAIN.csv",index_col=0)
test = pd.read_csv("TEST.csv",index_col=0)

In [3]:
train.head()
print('New dataset shape {}'.format(Counter(train["TARGET"])))

New dataset shape Counter({1: 60750, 0: 7755})


In [4]:
X = train.drop("TARGET", axis=1)
Y = train["TARGET"]
X_test = test.drop("TARGET", axis=1)
Y_test = test["TARGET"]

In [6]:
clf = RandomForestClassifier(n_estimators = 100)#, max_depth=25, criterion = "gini", min_samples_split=10)
clf.fit(X, Y)
pred=clf.predict(X_test)
print(classification_report(Y_test, pred))


             precision    recall  f1-score   support

          0       0.42      0.01      0.02      3409
          1       0.88      1.00      0.94     25951

avg / total       0.83      0.88      0.83     29360



In [12]:
clf = RandomForestClassifier(n_estimators = 100)#, max_depth=25, criterion = "gini", min_samples_split=10)
clf.fit(X, Y)
probs=clf.predict_proba(X_test)
probs

array([[0.03, 0.97],
       [0.01, 0.99],
       [0.23, 0.77],
       ...,
       [0.01, 0.99],
       [0.22, 0.78],
       [0.05, 0.95]])

In [23]:
probs[:, 0]

def filterp(th,ProbClass1):
    """ Given a treshold "th" and a set of probabilies of belonging to class 1 "ProbClass1", return predictions """ 
    y=np.zeros(ProbClass1.shape[0])
    for i,v in enumerate(ProbClass1):
        if ProbClass1[i]>th:
            y[i]=1
    return y  
for th in range(4):
    print('\n', th*0.1)
    npred = filterp(th*0.1,probs[:,0])
    print(classification_report(Y_test, npred))
    print(confusion_matrix(Y_test, npred))
#


 0.0
             precision    recall  f1-score   support

          0       0.05      0.00      0.01      3409
          1       0.88      0.99      0.94     25951

avg / total       0.79      0.88      0.83     29360

[[    9  3400]
 [  182 25769]]

 0.1
             precision    recall  f1-score   support

          0       0.08      0.32      0.12      3409
          1       0.85      0.50      0.63     25951

avg / total       0.76      0.48      0.57     29360

[[ 1085  2324]
 [13042 12909]]

 0.2
             precision    recall  f1-score   support

          0       0.10      0.75      0.18      3409
          1       0.79      0.12      0.21     25951

avg / total       0.71      0.19      0.21     29360

[[ 2556   853]
 [22798  3153]]

 0.30000000000000004
             precision    recall  f1-score   support

          0       0.11      0.92      0.20      3409
          1       0.68      0.02      0.04     25951

avg / total       0.61      0.13      0.06     29360

[[ 3132

             precision    recall  f1-score   support

          0       0.10      0.75      0.18      3409
          1       0.79      0.12      0.21     25951

avg / total       0.71      0.19      0.21     29360

